apiVersion: v1
kind: Pod
metadata:
  name: env-secret-pod
spec:
  containers:
    - name: app-container
      image: busybox
      # Comando che stampa le variabili d'ambiente USER e PASS e poi attende per 3600 secondi altrimenti il Pod termina subito per come funziona Busybox
      command: ["sh", "-c", "echo USER=$USERNAME && echo PASS=$PASSWORD && sleep 3600"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: password
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-secret-pod
spec:
  containers:
    - name: app-container
      image: busybox
      # Comando che stampa le variabili d'ambiente USER e PASS e poi attende per 3600 secondi altrimenti il Pod termina subito per come funziona Busybox
      command: ["sh", "-c", "cat /etc/secret-data/username; echo; cat /etc/secret-data/password; echo && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-data"
          readOnly: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: secret-volume
      secret:
        secretName: example-secret
