# Crea un generico ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: my-namespace
---
# Crea un Role in lettura sui pods nel namespace "my-namespace"
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: my-namespace
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
# Crea un RoleBinding per associare il Role al ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: my-namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: my-namespace
---
# Assegna il ServiceAccount al Pod
apiVersion: v1
kind: Pod
metadata:
  name: reader-app
  namespace: my-namespace
spec:
  serviceAccountName: pod-reader-sa
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
