name: my-example-azure.apps.backend
description: Microstack for backend application
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
