apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-namaspace
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
