# Espone l'applicazione backend all'esterno sulla porta 30080 tramite un NodePort
# Dall'esterno si può accedere all'applicazione backend tramite http://<IP-nodo>:30080
# Il service internamente al cluster è raggiungibile tramite il nome "backend-service" e la porta 80
# Dentro il container l'applicazione ascolta sulla porta 8080
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80 # Porta del Service (ClusterIP)
      targetPort: 8080 # Porta del container
      nodePort: 30080 # Porta esposta su ogni nodo
