name: my-example-minikube.monitoring
description: Microstack for cluster observability
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
