name: my-example-azure.apps.frontend
description: Microstack for frontend application
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
