apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  # non serve il namespace perchè è un oggetto Cluster-wide
provisioner: hostpath.csi.k8s.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
