apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
