services:
  backend:
    image: my-example-image-be
    # Per evitare di scaricare una immagine presente sul registry con lo stesso nome di quella locale per errore
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.multistage
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    image: my-example-image-fe
    # Per evitare di scaricare una immagine presente sul registry con lo stesso nome di quella locale per errore
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 81:80
    environment:
      API_URL: "http://localhost:8000"

  mongodb:
    image: mongo:8.0.10
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    env_file:
      - ./mongo-express/.env
    depends_on:
      - mongodb

volumes:
  mongo-data:
