name: my-example-minikube.infra
description: Microstack for infrastructure base components
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
