name: mysql-database

services:
  mysql:
    image: mysql:lts
    container_name: mysql-8.4.5-lts
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    name: mysql-data-volume
